# Generated by Django 2.0 on 2018-01-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='copy_markup',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
