# Generated by Django 2.0 on 2018-01-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180112_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='copy_markup',
            new_name='content',
        ),
    ]
