# Generated by Django 2.0.1 on 2018-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180125_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
